services:
  postgres:
    image: postgres:17
    container_name: postaddress_postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro,z

volumes:
  postgres-data:
