spring:
  application:
    name: postaddress-address-book
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
  mvc:
    format:
      date-time: iso
